### ISSUE TITLE
Keep Pressure Plates 4 incorrectly shown as inaccessible in tracker

### ISSUE THREAD

**Issue by Hagnkerchief** [NewSoupVi/witness_archipelago_tracker#1]
Pressure Plate 2 was missing mechanic, but is not required to access Pressure Plate 3 and 4 and the check.

[spoilerlog.txt](https://github.com/NewSoupVi/witness_archipelago_tracker/files/8802279/spoilerlog.txt)

**Comment by NewSoupVi** [comment]
The AP logic actually requires Pressure Plate 2 because I don't consider this "common knowledge". But I should add it as a "trick" (yellow) into the PopTracker pack at the very least :)
