### ISSUE TITLE
Simple Doors Shuffle: logic errors

### ISSUE THREAD

**Issue by JCBoorgo** [NewSoupVi/witness_archipelago_tracker#10]
VoD link: https://www.twitch.tv/videos/1620730363
Everything referenced here is in Map view because it's the only one I use
Around 1:31:10 -- in the Quarry Boathouse node, after receiving Stars, the Stars & Eraser & Shapers Row, Shortcut Door Panel, and the Quarry Laser in its own node all lit up as accessible without the Quarry Boathouse Barriers having been found
Around 2:33:50 -- in the Keep, Pressure Plates 4 and Keep Tower Laser were lit up after finding Symmetry, but Keep Pressure Plates Doors hadn't been found yet

Happened on v0.3.5 prerelease 1

**Comment by Exempt-Medic** [comment]
This has been fixed in later releases of the tracker with updated doors logic.
