### ISSUE TITLE
Tracker doesn't correctly count greenhouse/monastery/shadow lasers towards progress

### ISSUE THREAD

**Issue by Color-Printer** [NewSoupVi/witness_archipelago_tracker#15]
Not sure about other settings, but on

shuffle unrandomized: off
difficulty: normal
randomize symbols: on
shuffle lasers: off
door shuffle: panels

the tracker doesn't correctly count the three lasers that are turned on by default (or by other triggers, i'm not sure specifically how the archipelago version handles it) and there is no way to turn them on via the map or by clicking the laser icon. i have to manually lower the laser requirement from 7 to 4 in order to allow mountain to be accessible in logic

**Comment by Exempt-Medic** [comment]
This has since been fixed by various updates to the tracker, including better laser tracking and allowing you to manually change the number of lasers.
