### ISSUE TITLE
Mountain Elevator Discarded Panel shows as check even when discarded panels are disabled.

### ISSUE THREAD

**Issue by Ryuluce** [NewSoupVi/witness_archipelago_tracker#2]
The discarded panel in the second layer of the mountain next to the elevator is showing up as an enabled check in the tracker, even when discarded panels are disabled. The actual randomizer logic is working fine, since verifying available checks in Archipelago text client or the website doesn't show the elevator discarded panel.

**Comment by NewSoupVi** [comment]
Good catch - It's already fixed, I just haven't pushed it, will be fixed in next version :)
