### ISSUE TITLE
Discards incorrectly marked as accessible

### ISSUE THREAD

**Issue by octylFractal** [NewSoupVi/witness_archipelago_tracker#32]
I don't have the triangles, but the tracker still thinks I can access the discard panel checks. Specifically with "Outside Glass Factory" > "Rooftop Discard".

**Comment by Exempt-Medic** [comment]
Any more information you have about this would be helpful. What tracker version? What Archipelago version? What room? Is the error still available for investigation/testing? Were you playing on Expert by chance?

**Comment by octylFractal** [comment]
This occurred with Tracker 0.4.4.2, Archipelago 0.4.4. I will be trying this out again in 0.4.5 to see if it persists at some point. 

Assuming you mean what Archipelago room, it seems that has closed, when I am at my computer again I can upload a copy of the generated zip. I do not think it was on Expert. I'm not sure how to tell, though.

**Comment by Exempt-Medic** [comment]
Assuming the room was hosted on the site, and you haven't deleted your cookies, you should be able to find it at https://archipelago.gg/user-content . You could then connect to it with a tracker and open the settings panel (the gear icon) to check the settings, or you could check the spoiler log, if one was generated.

**Comment by octylFractal** [comment]
The spoiler log is https://archipelago.gg/dl_spoiler/5QFdPi97S9Sj9SVV859yMA.

**Comment by octylFractal** [comment]
Playing on 0.4.5 of both the Tracker and Archipelago, there seems to be no issues with this any more.
